import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { test } from 'node:test';
import { WorkflowStore } from '../src/workflows/store.js';
import type { Workflow } from '../src/workflows/schema.js';
import { createDashboardServer } from '../src/app/server.js';
import { SqliteTrace } from '../src/trace/sqlite-trace.js';
import { initialState } from '../src/graph/state.js';
import type { WorkflowExecutionRequest } from '../src/workflows/execution.js';
import type { BudgetOverride } from '../src/runtime/model-budget.js';

test('流程库固定版本只读预览、参数校验与证据回看/报告下载', { timeout: 60000 }, async () => {
  const dir = mkdtempSync(join(tmpdir(), 'workflow-library-'));
  const store = new WorkflowStore(join(dir, 'workflows.sqlite'));
  const candidate: Workflow = { id: 'write-example', version: 1, status: 'candidate', environment: 'windows',
    taskPattern: '输入 {{value}}', inputs: [{ name: 'value', example: '示例文字' }], preconditions: [],
    steps: [{ goal: '输入 {{value}}', action: { kind: 'keypress', keys: 'space' }, preferredMethods: [],
      successCondition: { kind: 'text_includes', value: '{{value}}' } }], successConditions: { pageTextIncludes: '{{value}}' },
    knownFailures: [], sourceTaskId: 'origin', sourceTrace: 'runs.sqlite', createdAt: '', successCount: 0, failureCount: 0 };
  store.addCandidate(candidate); store.recordReplay(candidate.id, 1, 'task-1', true);
  store.addCandidate({ ...candidate, taskPattern: '新版输入 {{value}}' });
  const before = store.list();
  const trace = new SqliteTrace(join(dir, 'runs.sqlite'));
  const state = initialState('task-1', '证据回看测试');
  for (const step of [1, 2]) trace.save('observe', { ...state, step, observation: { screenshot: join(dir, '.artifacts', 'missing.png') } });
  trace.save('finish', { ...state, step: 2, status: 'done', workflowRef: { id: candidate.id, version: 1, values: { value: 'A' }, definitionHash: 'recorded-hash' } });
  trace.close();
  const submitted: WorkflowExecutionRequest[] = [];
  const submittedBudgets: Array<BudgetOverride | undefined> = [];
  const desktopTarget = { providerId: 'synthetic-provider', environmentId: 'desktop-one' };
  const submittedTargets: unknown[] = [];
  const server = createDashboardServer(dir, {
    submit() { throw new Error('must use versioned submission'); },
    desktopOptions: async () => [{ ...desktopTarget, kind: 'physical', executable: true }],
    submitWorkflow(request, budget, target) { submitted.push(request); submittedBudgets.push(budget); submittedTargets.push(target); return 'task-1'; }, resume() {}, pause() {}, continue() {},
  });
  await new Promise<void>(done => server.listen(0, '127.0.0.1', done));
  const address = server.address(); if (!address || typeof address === 'string') throw new Error('No port');
  const base = `http://127.0.0.1:${address.port}`;
  let browser: import('playwright').Browser | undefined;
  try {
    const list = await (await fetch(`${base}/api/workflows`)).json(); assert.equal(list.workflows.length, 2);
    const detail = await (await fetch(`${base}/api/workflows/write-example/1`)).json();
    assert.equal(detail.workflow.version, 1); assert.equal(detail.runs[0].taskId, 'task-1');
    assert.equal((await fetch(`${base}/api/workflows/write-example/999`)).status, 404);
    assert.equal((await fetch(`${base}/api/workflows/write-example/1.5`)).status, 400);
    const preview = (values: unknown, origin = base) => fetch(`${base}/api/workflows/write-example/1/preview`, {
      method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify({ values }) });
    const response = await preview({ value: '<测试 & "内容">' }); const result = await response.json();
    assert.equal(result.executed, false); assert.equal(result.version, 1);
    assert.equal(result.steps[0].successCondition.value, '<测试 & "内容">');
    for (const values of [{}, { value: 1 }, { value: ' ' }, { value: 'x', extra: 'x' }, { value: 'x'.repeat(301) }]) assert.equal((await preview(values)).status, 400);
    assert.equal((await preview({ value: 'x' }, 'http://evil.example')).status, 403);
    const execute = (body: object, origin = base) => fetch(`${base}/api/workflows/write-example/1/execute`, {
      method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify(body) });
    const executionBody = { destination: 'windows', definitionHash: detail.definitionHash, values: { value: 'x' } };
    assert.equal((await execute(executionBody, 'http://evil.example')).status, 403);
    assert.equal((await execute({ ...executionBody, definitionHash: 'stale' })).status, 409);
    assert.equal((await execute({ ...executionBody, destination: 'host' })).status, 400);
    assert.equal(submitted.length, 0);
    process.env.PLAYWRIGHT_BROWSERS_PATH ??= resolve('.playwright-browsers');
    const { chromium } = await import('playwright'); browser = await chromium.launch();
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    await page.route('**/api/desktop/control', route => route.fulfill({ json: { mode: 'PAUSED', workerReady: true, taskId: null } }));
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(base);
    await page.route('**/api/workflows', route => route.fulfill({ status: 503, json: { error: '测试连接故障' } }), { times: 1 });
    await page.getByRole('button', { name: '工作流', exact: true }).click();
    await page.getByRole('button', { name: '重试读取流程', exact: true }).waitFor();
    assert.equal(await page.locator('.workflow-card').count(), 0);
    assert.match(await page.locator('.library-message').innerText(), /读取失败/);
    await page.getByRole('button', { name: '重试读取流程', exact: true }).click();
    await page.locator('.workflow-card').click();
    await page.getByLabel('流程版本', { exact: true }).selectOption('1');
    await page.getByLabel('value', { exact: true }).fill('测试值');
    await page.locator('#workflow-desktop-target').selectOption(JSON.stringify(['synthetic-provider', 'desktop-one']));
    assert.equal(await page.getByRole('button', { name: '执行此版本', exact: true }).isDisabled(), true);
    await page.getByRole('button', { name: '预览步骤（不执行）', exact: true }).click();
    await page.getByText('v1 参数预览 · 未执行任何动作', { exact: true }).waitFor();
    assert.match(await page.locator('.workflow-preview').innerText(), /测试值/);
    assert.equal(await page.getByRole('button', { name: '执行此版本', exact: true }).isEnabled(), true);
    await page.getByLabel('value', { exact: true }).fill('其他值');
    assert.match(await page.locator('.workflow-preview').innerText(), /请重新预览/);
    assert.equal(await page.getByRole('button', { name: '执行此版本', exact: true }).isDisabled(), true);
    await page.getByLabel('流程版本', { exact: true }).selectOption('2');
    await page.getByRole('heading', { name: '新版输入 {{value}}', exact: true }).waitFor();
    assert.equal(await page.locator('.workflow-preview').innerText(), '');
    assert.equal(await page.getByLabel('value', { exact: true }).inputValue(), '', '新版本不继承旧版本参数');
    await page.reload();
    await page.locator('.workflow-card').click();
    await page.getByLabel('流程版本', { exact: true }).selectOption('1');
    assert.equal(await page.getByLabel('value', { exact: true }).inputValue(), '其他值', '刷新保留当前版本草稿');
    assert.equal(await page.locator('.workflow-preview').innerText(), '', '恢复草稿不复用旧预览');
    await page.getByRole('button', { name: '预览步骤（不执行）', exact: true }).click();
    await page.getByText('v1 参数预览 · 未执行任何动作', { exact: true }).waitFor();
    await page.getByText('本次模型预算（可选）', { exact: true }).click();
    await page.locator('.workflow-budget-options').getByLabel('DeepSeek 最多调用次数').fill('3');
    await page.locator('#workflow-desktop-target').selectOption(JSON.stringify(['synthetic-provider', 'desktop-one']));
    await page.getByRole('button', { name: '执行此版本', exact: true }).click();
    await page.waitForURL('**/#/history?task=web-tasks.sqlite%2Ftask-1');
    assert.equal(submitted.length, 1);
    assert.deepEqual(submitted[0], { id: 'write-example', version: 1, ...executionBody, values: { value: '其他值' } });
    assert.deepEqual(submittedBudgets[0], { deepseek: { maxCalls: 3 } });
    assert.deepEqual(submittedTargets[0], desktopTarget);
    await page.getByRole('button', { name: '工作流', exact: true }).click();
    await page.locator('.workflow-card').click();
    await page.getByLabel('value', { exact: true }).fill('试运行参数');
    const trialButton = page.getByRole('button', { name: '试运行此候选版本', exact: true });
    assert.equal(await trialButton.isDisabled(), true);
    await page.getByRole('button', { name: '预览步骤（不执行）', exact: true }).click();
    await page.getByText('v2 参数预览 · 未执行任何动作', { exact: true }).waitFor();
    await page.locator('#workflow-desktop-target').selectOption(JSON.stringify(['synthetic-provider', 'desktop-one']));
    await trialButton.click();
    await page.waitForURL('**/#/history?task=web-tasks.sqlite%2Ftask-1');
    assert.equal(submitted.length, 2); assert.equal(submitted[1].trial, true);
    assert.equal(submitted[1].version, 2); assert.deepEqual(submitted[1].values, { value: '试运行参数' });
    await page.getByRole('button', { name: '工作流', exact: true }).click();
    await page.getByRole('searchbox', { name: '搜索流程', exact: true }).fill('不存在');
    assert.equal(await page.locator('.workflow-card').count(), 0);
    await page.getByRole('button', { name: '清除流程筛选', exact: true }).click();
    await page.locator('.workflow-card').click();
    assert.equal(await page.locator('.workflow-card').count(), 1, '版本聚合为一个流程');
    await page.getByText('编辑名称与说明', { exact: true }).click();
    await page.getByLabel('流程名称', { exact: true }).fill('示例输入流程');
    await page.getByLabel('用途说明', { exact: true }).fill('用参数填入文字');
    await page.getByRole('button', { name: '保存名称与说明', exact: true }).click();
    await page.getByText('名称与说明已保存', { exact: true }).waitFor();
    const updateMetadata = (body: object, origin = base) => fetch(`${base}/api/workflows/write-example/metadata`, {
      method: 'PUT', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify(body) });
    const metadataBody = { displayName: '不应保存', description: '', revision: 0 };
    assert.equal((await updateMetadata(metadataBody)).status, 409, '旧修订不能覆盖保存');
    assert.equal((await updateMetadata({ ...metadataBody, revision: 1 }, 'http://evil.example')).status, 403);
    assert.equal((await updateMetadata({ ...metadataBody, displayName: ' ', revision: 1 })).status, 400);
    const savedDetail = await (await fetch(`${base}/api/workflows/write-example/1`)).json();
    assert.equal(savedDetail.definitionHash, detail.definitionHash, '改名不改变执行摘要');
    assert.equal(savedDetail.metadata.displayName, '示例输入流程');
    assert.equal(savedDetail.metadata.revision, 1);
    await page.reload();
    await page.getByRole('searchbox', { name: '搜索流程', exact: true }).fill('示例输入流程');
    await page.locator('.workflow-card').click();
    await page.getByRole('heading', { name: '示例输入流程', exact: true }).waitFor();
    await page.getByLabel('流程版本', { exact: true }).selectOption('1');
    await page.getByText('用参数填入文字', { exact: true }).first().waitFor();
    mkdirSync(resolve('.artifacts/web-workbench'), { recursive: true });
    await page.screenshot({ path: resolve('.artifacts/web-workbench/workflow-library.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.getByRole('button', { name: '任务', exact: true }).click();
    await page.locator('.run-card').filter({ hasText: '证据回看测试' }).click();
    await page.getByRole('heading', { name: '证据回看测试' }).waitFor();
    await page.locator('#task-recorded').getByText('截图文件不可读取，请查看执行记录中的文字证据。', { exact: true }).waitFor();
    assert.equal(await page.locator('#task-recorded img').isVisible(), false);
    assert.match(await page.locator('.workflow-binding').innerText(), /v1/);
    const downloadEvent = page.waitForEvent('download');
    await page.getByRole('link', { name: '下载执行报告（JSON）' }).click();
    await (await downloadEvent).saveAs(join(dir, 'report.json'));
    const report = JSON.parse(readFileSync(join(dir, 'report.json'), 'utf8'));
    assert.equal(report.run.taskId, 'task-1'); assert.equal(report.run.workflowRef.version, 1);
    await page.locator('.task-diagnostics > summary').click();
    await page.getByRole('button', { name: '步骤证据', exact: true }).click();
    await page.getByRole('button', { name: '上一步', exact: true }).click();
    assert.match(await page.locator('.evidence-navigation').innerText(), /第 1 步/);
    await page.getByText('截图文件缺失或不可读取；此步骤的文字证据仍保留。', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '上一步', exact: true }).isEnabled(), false);
    await page.getByRole('button', { name: '下一步', exact: true }).click();
    assert.match(await page.locator('.evidence-navigation').innerText(), /第 2 步/);
    assert.deepEqual(errors, []); assert.deepEqual(store.list(), before);
    const candidateDetail = await (await fetch(`${base}/api/workflows/write-example/2`)).json();
    const publish = (body: object, origin = base) => fetch(`${base}/api/workflows/write-example/2/publish`, {
      method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify(body) });
    const publishBody = { definitionHash: candidateDetail.definitionHash, successCount: 0, failureCount: 0 };
    assert.equal((await publish(publishBody, 'http://evil.example')).status, 403);
    assert.equal((await publish(publishBody)).status, 409, '无成功试运行不能发布');
    store.recordReplay('write-example', 2, 'trial-success', true, undefined, candidateDetail.definitionHash, 'record_only');
    assert.equal(store.get('write-example', 2)?.status, 'candidate');
    assert.equal((await publish(publishBody)).status, 409, '旧回放计数不能发布');
    await page.reload();
    await page.getByRole('button', { name: '工作流', exact: true }).click();
    await page.locator('.workflow-card').click();
    await page.getByLabel('流程版本', { exact: true }).selectOption('2');
    await page.getByText('审核并发布此候选版本').click();
    await page.getByRole('button', { name: '确认发布为已验证' }).click();
    await page.getByText('v2 · 已验证 · 整任务流程', { exact: false }).waitFor();
    assert.equal(store.get('write-example', 2)?.status, 'verified');
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close(); await new Promise<void>(resolve => server.close(() => resolve()));
    store.close(); rmSync(dir, { recursive: true, force: true });
  }
});
